#!/bin/bash

if [ -d "/installer" ]; then
    echo "Starting first run configuration..."
    /usr/local/bin/first_run
else
  if [ "$DB_NAME" != "" ]; then
    /etc/init.d/mysql start
  fi
fi

/etc/init.d/apache2 start

echo "Done."

read -p "Press Return to Close..."